from tkinter import *
master = Tk()
master.geometry('550x550')
Label(master, text='Full Name',width="20",height="5").grid(row=0) 
Label(master, text='Department ',width="10", height="10").grid(row=1)
Label(master, text='Passed Out',width="10", height="10").grid(row=2) 
e1 = Entry(master) 
e2 = Entry(master)
e3 = Entry(master) 
e1.grid(row=0, column=1) 
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
Label(master, text='').grid(row=3) 
Button(master,text="Submit", height="02", width="20").grid(row=3,column=1)
mainloop() 
